blank_issues_enabled: false
contact_links:
  - name: 🌐 Profferio website
    url: https://www.profferio.com
    about: Learn more, see features and request a demo or quote.
  - name: 📨 Contact us
    url: https://www.profferio.com/info/
    about: Get in touch with the Profferio team directly.
